---
experiment_name: "J_new"

data:
  path: "/Users/giorgioaurina/Desktop/Paolo/Progressive-Multifidelity-Learning/data/ice/"
  sequential_mask: False
  scaling: "SV" #"SV + Reynolds"
  seq_len: 365 #year
  seq_freq: 30 #month
  dimensions: 
    level_0: None #set manually
    level_1: None #set manually
    level_2: None #set manuallly
    #level_3: 577
    output: None #set manually
    parameters_dim: 1

model:
  checkpoints_path: "/checkpoints"
  #spatial_encoders_dim:
  #  level_2: 8
  load_model: False
  save_model: True
  embedding_dim: 64 #80
  n_heads: 2 #1
  mask_embeddings: False
  n_transformer_blocks: 1
  dropout: 0.2 #0.1

logging:
  wandb: False #Quando è True: registra metriche, loss, parametri del modello, e grafici in tempo reale sul cloud di W&B
  gradients: False #Quando è True: salva informazioni sui gradienti (magnitudine, distribuzione) per debugging
  save_model: True #Quando è True: salva il file .pt con i pesi del modello migliore

training:
  epochs: 300 #!
  batch_size: 16  # Reduced from 64 to prevent CUDA OOM
  optim_params:
    learning_rate: 0.1 #0.5
    warmup: 800 
    betas:
      - 0.9
      - 0.98
    eps: 1e-9
    weight_decay: 1e-4
